### PR TITLE
Adding Esing new version

### PR DESCRIPTION
**Pull request by PedroKravetz**
There is a new version of the Esing, that works correctly in 7.x versions, I altered the script, Read me and the amp files

### CODE REVIEW

**Comment by PedroKravetz** [comment]
They don't solve the currently problem of the 7.4 version, but now the signature works

**Comment by PedroKravetz** [comment]
I just saw that i forgot to put the upgrade the repo amp, now it is correct

**Comment by PedroKravetz** [comment]
I solved the problem that happenned in Alfresco 7.4 version, I corrected it, added the amps in this repository and removed the if on the index.js to accept if it was 7.4

**Comment by PedroKravetz** [comment]
#175

**Comment by aborroy** [comment]
Thanks for your contribution, @PedroKravetz

**Pull request merged**
